// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWY2vubzBJHMe3jpQSkf2fhuSLadm4bk',
    appId: '1:763041501773:web:3f5a1646f430f5a5934204',
    messagingSenderId: '763041501773',
    projectId: 'chat-3b0e1',
    authDomain: 'chat-3b0e1.firebaseapp.com',
    storageBucket: 'chat-3b0e1.firebasestorage.app',
    measurementId: 'G-NQJS8MMXD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQEjAzEoi1RoqUc009aNvOS3T4hfVio90',
    appId: '1:763041501773:android:6784e104b832d116934204',
    messagingSenderId: '763041501773',
    projectId: 'chat-3b0e1',
    storageBucket: 'chat-3b0e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-tuN_63nRZlTS9nJVNXVOnFSrqtuUUwE',
    appId: '1:763041501773:ios:4760d35c331fa3b2934204',
    messagingSenderId: '763041501773',
    projectId: 'chat-3b0e1',
    storageBucket: 'chat-3b0e1.firebasestorage.app',
    iosBundleId: 'com.example.secureChat',
  );
}
